name: source
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.19.1
  jaspr_content: ^0.2.0
  jaspr_flutter_embed: ^0.4.6
  jaspr_router: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.5+1
  jaspr_builder: ^0.19.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jaspr_lints: ^0.4.0

jaspr:
  mode: static

flutter:
  uses-material-design: true
